# Generated by Django 6.1 on 2026-08-20 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_id', models.CharField(max_length=100, unique=True)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('battery_model', models.CharField(blank=True, max_length=100)),
                ('battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
