# Generated by Django 6.1 on 2026-08-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('soc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cycle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('charging_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energy_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('energy_discharged', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms_data', to='batteries.battery')),
            ],
        ),
    ]
