# Generated by Django 6.1 on 2026-08-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0002_bmsdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmsdata',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='charging_duration',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='current',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='cycle_count',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='energy_charged',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='energy_discharged',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='soc',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='bmsdata',
            name='voltage',
        ),
        migrations.AddField(
            model_name='bmsdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='bms_uploads/'),
        ),
        migrations.AlterField(
            model_name='bmsdata',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms_uploads', to='batteries.battery'),
        ),
    ]
