# Generated by Django 6.1 on 2026-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0003_rename_created_at_bmsdata_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmsdata',
            name='file',
            field=models.FileField(upload_to='bms_uploads/'),
        ),
    ]
