# Generated by Django 6.1 on 2026-08-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0004_alter_bmsdata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('cycle_count', models.IntegerField(blank=True, null=True)),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('min_temperature', models.FloatField(blank=True, null=True)),
                ('max_temperature', models.FloatField(blank=True, null=True)),
                ('avg_voltage', models.FloatField(blank=True, null=True)),
                ('min_voltage', models.FloatField(blank=True, null=True)),
                ('max_voltage', models.FloatField(blank=True, null=True)),
                ('avg_current', models.FloatField(blank=True, null=True)),
                ('total_discharge_duration', models.FloatField(blank=True, null=True)),
                ('bms_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='batteries.bmsdata')),
            ],
        ),
    ]
