# Generated by Django 6.1 on 2026-08-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteries', '0005_bmsmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='chemistry',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='battery',
            name='nominal_voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
