"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path

import os
from dotenv import load_dotenv

# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (git-ignored) — holds Supabase DB credentials.
# Falls back to the original local PostgreSQL config when absent.
load_dotenv(BASE_DIR / ".env")


# ============================================================
# SECURITY
# ============================================================

# Safe default (False) for production. Set DEBUG=True in local .env for dev.
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

SECRET_KEY = os.environ.get("SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        # Local development fallback only. Never used in production.
        SECRET_KEY = "django-insecure-local-dev-fallback-key-do-not-use-in-prod"
    else:
        raise RuntimeError(
            "SECRET_KEY environment variable is required when DEBUG is False."
        )

# Comma-separated hostnames, e.g. ALLOWED_HOSTS=your-app.onrender.com
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "").split(",")
    if host.strip()
]
# Local development convenience only (harmless in production).
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [

    # Django built-in apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "corsheaders",

    # Our apps
    "users",
    "batteries",
    "analysis",
    "passport",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    # Allows React frontend to communicate with Django backend
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = "config.urls"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# WSGI
# ============================================================

WSGI_APPLICATION = "config.wsgi.application"


# ============================================================
# DATABASE - POSTGRESQL
# Values come from .env (Supabase). Defaults below preserve the
# original local PostgreSQL configuration as a fallback.
# ============================================================

_db_options = {}
if os.environ.get("DB_SSLMODE"):
    _db_options["sslmode"] = os.environ["DB_SSLMODE"]

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.postgresql"),

        "NAME": os.environ.get("DB_NAME", "ev_battery_db"),

        "USER": os.environ.get("DB_USER", "ev_hackathon"),

        "PASSWORD": os.environ.get("DB_PASSWORD", "sih2026"),

        "HOST": os.environ.get("DB_HOST", "localhost"),

        "PORT": os.environ.get("DB_PORT", "5432"),

        "OPTIONS": _db_options,
    }
}


# ============================================================
# CUSTOM USER MODEL
# ============================================================

AUTH_USER_MODEL = "users.User"


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME":
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME":
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = "static/"

# Render/production: collectstatic target (served by WhiteNoise).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Render terminates TLS at its proxy — trust its header so Django
# knows requests are HTTPS. Safe locally (header is not sent).
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ============================================================
# MEDIA FILES
# Later used for BMS CSV, certificates, passport etc.
# ============================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# DJANGO REST FRAMEWORK
# ============================================================

REST_FRAMEWORK = {

    # JWT authentication
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    # By default, API requires login
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}


# ============================================================
# CORS
# React frontend → Django backend
# ============================================================

# Production: comma-separated allowlist, e.g.
# CORS_ALLOWED_ORIGINS=https://your-app.netlify.app
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(",")
    if origin.strip()
]

# Allow-all ONLY while local debugging (DEBUG=True). Never in production.
CORS_ALLOW_ALL_ORIGINS = DEBUG


# ============================================================
# EMAIL
# Development mode
# Emails will appear in the terminal instead of being sent.
# ============================================================

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# this is used for media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# GEMINI API CONFIGURATION
# ============================================================

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_RECOMMENDATION_API_KEY = os.environ.get("GEMINI_RECOMMENDATION_API_KEY", GEMINI_API_KEY)
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")

# Used as the threshold for second-life recommendations.
# If SoH > threshold, battery is considered healthy and EV_CONTINUE.
SECOND_LIFE_SOH_THRESHOLD = 80