# Generated by Django 6.1 on 2026-08-22 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_batteryanalysis_degradation_factors_and_more'),
        ('batteries', '0004_alter_bmsdata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_id', models.CharField(max_length=100, unique=True)),
                ('current_soh', models.FloatField(blank=True, null=True)),
                ('safety_risk', models.CharField(blank=True, max_length=50, null=True)),
                ('degradation_factors', models.JSONField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('second_life_status', models.CharField(blank=True, max_length=200, null=True)),
                ('certification_status', models.CharField(default='Not Certified', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passports', to='analysis.batteryanalysis')),
                ('battery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='batteries.battery')),
            ],
        ),
    ]
