# Generated by Django 6.1 on 2026-08-22 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batterypassport',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterypassport',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batterypassport',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_passports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batterypassport',
            name='certification_status',
            field=models.CharField(choices=[('NOT_CERTIFIED', 'Not Certified'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_CERTIFIED', max_length=50),
        ),
    ]
