# Generated by Django 6.1 on 2026-09-01 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_batteryanalysis_degradation_factors_and_more'),
        ('batteries', '0006_battery_chemistry_battery_nominal_voltage'),
        ('passport', '0002_batterypassport_verification_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterypassport',
            name='battery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='batteries.battery'),
        ),
        migrations.AddConstraint(
            model_name='batterypassport',
            constraint=models.UniqueConstraint(fields=('battery', 'analysis'), name='unique_battery_analysis_passport'),
        ),
    ]
