# Generated by Django 6.1 on 2026-08-20 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batteries', '0004_alter_bmsdata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soh', models.FloatField(blank=True, null=True)),
                ('safety_risk', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bms_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='batteries.bmsdata')),
            ],
        ),
    ]
