# Generated by Django 6.1 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryanalysis',
            name='degradation_factors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batteryanalysis',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batteryanalysis',
            name='second_life',
            field=models.TextField(blank=True, null=True),
        ),
    ]
